### ISSUE TITLE
error require stack

### ISSUE THREAD

**Issue by dempotato** [Kloct/tera-client#5]
(node:57364) UnhandledPromiseRejectionWarning: Error: Cannot find module 'log'
Require stack:
- C:\Users\eejt\Desktop\tera-client-master\bin\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:17)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at init (C:\Users\eejt\Desktop\tera-client-master\bin\index.js:4:14)
    at Object.<anonymous> (C:\Users\eejt\Desktop\tera-client-master\bin\index.js:178:1)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
(node:57364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:57364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Press any key to continue . . .

I got this error after keying in my account details,
sorry im really new so i dont know what to do, i downloaded node.js as well already

**Comment by Kloct** [comment]
Try the [cli branch](https://github.com/Kloct/tera-client/tree/cli) instead. 👍

The master branch doesn't include any dependencies pre-installed.
